name: Build the main branch
on:
  push:
    branches:
      - ci/setup-build-main-branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install the package dependencies
        run: pip install .
      - name: Run the tests
        run: pytest
